apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
  - image: us.gcr.io/ticketing-dev-368907/auth
    context: auth
    sync: # how to handle the files in our dir
      manual:
      - src: src/**/*.ts # set of files skaffold needs to watch. Go to the src dir and get all the files with the extension of .ts
        dest: .
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: ticketing-dev-368907
manifests:
  rawYaml:
  - ./infra/k8s/* # watch all these files
deploy:
  kubectl: {}